version: 2.1

jobs:
  built_38:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - run: echo 'export PYTHONPATH="${PYTHONPATH}:{HOME}:/circleci-python"' >> $BASH_ENV
      - run: python -c "import sys; print(sys.path)"


  testing_38:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - run: echo 'export PYTHONPATH="${PYTHONPATH}:{HOME}:/circleci-python"' >> $BASH_ENV
      - run: python -c "import sys; print(sys.path)"
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements.txt
      - run: pytest test/test_main.py


  built_39:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.9"
    steps:
      - checkout
      - run: echo 'export PYTHONPATH="${PYTHONPATH}:{HOME}:/circleci-python"' >> $BASH_ENV
      - run: python -c "import sys; print(sys.path)"


  testing_39:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.9"
    steps:
      - checkout
      - run: echo 'export PYTHONPATH="${PYTHONPATH}:{HOME}:/circleci-python"' >> $BASH_ENV
      - run: python -c "import sys; print(sys.path)"
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements.txt
      - run: pytest test/test_main.py


workflows:
  first_build_38:
    jobs:
      - built_38
      - testing_38:
          requires:
            - built_38

  first_build_39:
    jobs:
      - built_39
      - testing_39:
          requires:
            - built_39